version: '3'

x-common: &common
  build: .
  depends_on:
    - redis

services:
  web:
    <<: *common
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    <<: *common
    command: celery -A python_project worker --loglevel=info

  celery-beat:
    <<: *common
    command: celery -A python_project beat --loglevel=info
    volumes:
      - celerybeat-data:/app/celerybeat-schedule.db

volumes:
  celerybeat-data: