# Generated by Django 5.1.7 on 2025-05-26 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('lastname', models.CharField(max_length=50, verbose_name='Отчество')),
                ('department', models.CharField(max_length=2, verbose_name='Кафедра')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='IT1_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='Дата')),
                ('GroupIn900_1030', models.CharField(blank=True, default='', max_length=16, verbose_name='Группа на 9.00-10.30')),
                ('GroupIn1045_1215', models.CharField(blank=True, default='', max_length=16, verbose_name='Группа на 10.45-12.15')),
                ('GroupIn1300_1430', models.CharField(blank=True, default='', max_length=16, verbose_name='Группа на 13.00-14.30')),
                ('GroupIn1445_1615', models.CharField(blank=True, default='', max_length=16, verbose_name='Группа на 14.45-16.15')),
                ('GroupIn1630_1800', models.CharField(blank=True, default='', max_length=16, verbose_name='Группа на 16.30-18.00')),
                ('GroupIn1800_1930', models.CharField(blank=True, default='', max_length=16, verbose_name='Группа на 18.00-19.30')),
            ],
            options={
                'verbose_name': 'Группа в IT-1',
                'verbose_name_plural': 'Группы в IT-1',
            },
        ),
        migrations.CreateModel(
            name='IT2_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='Дата')),
                ('GroupIn900_1030', models.CharField(blank=True, default='', max_length=16, verbose_name='Группа на 9.00-10.30')),
                ('GroupIn1045_1215', models.CharField(blank=True, default='', max_length=16, verbose_name='Группа на 10.45-12.15')),
                ('GroupIn1300_1430', models.CharField(blank=True, default='', max_length=16, verbose_name='Группа на 13.00-14.30')),
                ('GroupIn1445_1615', models.CharField(blank=True, default='', max_length=16, verbose_name='Группа на 14.45-16.15')),
                ('GroupIn1630_1800', models.CharField(blank=True, default='', max_length=16, verbose_name='Группа на 16.30-18.00')),
                ('GroupIn1800_1930', models.CharField(blank=True, default='', max_length=16, verbose_name='Группа на 18.00-19.30')),
            ],
            options={
                'verbose_name': 'Группа в IT-2',
                'verbose_name_plural': 'Группы в IT-2',
            },
        ),
        migrations.CreateModel(
            name='IT3_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='Дата')),
                ('GroupIn900_1030', models.CharField(blank=True, default='', max_length=16, verbose_name='Группа на 9.00-10.30')),
                ('GroupIn1045_1215', models.CharField(blank=True, default='', max_length=16, verbose_name='Группа на 10.45-12.15')),
                ('GroupIn1300_1430', models.CharField(blank=True, default='', max_length=16, verbose_name='Группа на 13.00-14.30')),
                ('GroupIn1445_1615', models.CharField(blank=True, default='', max_length=16, verbose_name='Группа на 14.45-16.15')),
                ('GroupIn1630_1800', models.CharField(blank=True, default='', max_length=16, verbose_name='Группа на 16.30-18.00')),
                ('GroupIn1800_1930', models.CharField(blank=True, default='', max_length=16, verbose_name='Группа на 18.00-19.30')),
            ],
            options={
                'verbose_name': 'Группа в IT-3',
                'verbose_name_plural': 'Группы в IT-3',
            },
        ),
        migrations.CreateModel(
            name='IT4_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='Дата')),
                ('GroupIn900_1030', models.CharField(blank=True, default='', max_length=16, verbose_name='Группа на 9.00-10.30')),
                ('GroupIn1045_1215', models.CharField(blank=True, default='', max_length=16, verbose_name='Группа на 10.45-12.15')),
                ('GroupIn1300_1430', models.CharField(blank=True, default='', max_length=16, verbose_name='Группа на 13.00-14.30')),
                ('GroupIn1445_1615', models.CharField(blank=True, default='', max_length=16, verbose_name='Группа на 14.45-16.15')),
                ('GroupIn1630_1800', models.CharField(blank=True, default='', max_length=16, verbose_name='Группа на 16.30-18.00')),
                ('GroupIn1800_1930', models.CharField(blank=True, default='', max_length=16, verbose_name='Группа на 18.00-19.30')),
            ],
            options={
                'verbose_name': 'Группа в IT-4',
                'verbose_name_plural': 'Группы в IT-4',
            },
        ),
        migrations.CreateModel(
            name='Audiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IT1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.it1_db')),
                ('IT2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.it2_db')),
                ('IT3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.it3_db')),
                ('IT4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.it4_db')),
            ],
            options={
                'verbose_name': 'Занятость IT класса по датам',
                'verbose_name_plural': 'Занятость IT классов по датам',
            },
        ),
    ]
